# Stubs for networkx.algorithms.centrality.current_flow_closeness (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

from networkx.algorithms.centrality.flow_matrix import *

def current_flow_closeness_centrality(G, weight: Incomplete | None = None, dtype=..., solver: str = "lu"): ...

information_centrality = current_flow_closeness_centrality
