# Stubs for networkx.algorithms.centrality.current_flow_betweenness_subset (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

from networkx.algorithms.centrality.flow_matrix import *

def current_flow_betweenness_centrality_subset(
    G, sources, targets, normalized: bool = ..., weight: Incomplete | None = ..., dtype=..., solver: str = ...
): ...
def edge_current_flow_betweenness_centrality_subset(
    G, sources, targets, normalized: bool = ..., weight: Incomplete | None = ..., dtype=..., solver: str = ...
): ...
