# Stubs for networkx.algorithms.centrality.dispersion (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def dispersion(
    G,
    u: Incomplete | None = None,
    v: Incomplete | None = None,
    normalized: bool = True,
    alpha: float = 1.0,
    b: float = 0.0,
    c: float = 0.0,
): ...
