# Stubs for networkx.algorithms.centrality.percolation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def percolation_centrality(
    G, attribute: str = "percolation", states: Incomplete | None = None, weight: Incomplete | None = None
): ...
