# Stubs for networkx.algorithms.centrality.reaching (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def global_reaching_centrality(G, weight: Incomplete | None = ..., normalized: bool = ...): ...
def local_reaching_centrality(G, v, paths: Incomplete | None = ..., weight: Incomplete | None = ..., normalized: bool = ...): ...
