# Stubs for networkx.readwrite.adjlist (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def generate_adjlist(G, delimiter: str = ...) -> None: ...
def write_adjlist(G, path, comments: str = ..., delimiter: str = ..., encoding: str = ...) -> None: ...
def parse_adjlist(
    lines,
    comments: str = ...,
    delimiter: Incomplete | None = ...,
    create_using: Incomplete | None = ...,
    nodetype: Incomplete | None = ...,
): ...
def read_adjlist(
    path,
    comments: str = ...,
    delimiter: Incomplete | None = ...,
    create_using: Incomplete | None = ...,
    nodetype: Incomplete | None = ...,
    encoding: str = ...,
): ...
