from _typeshed import Incomplete

long = int
unicode = str
unichr = chr

def read_gml(path, label: str = "label", destringizer: Incomplete | None = None): ...
def parse_gml(lines, label: str = "label", destringizer: Incomplete | None = None): ...
def generate_gml(G, stringizer: Incomplete | None = None) -> None: ...
def write_gml(G, path, stringizer: Incomplete | None = None) -> None: ...
