# Stubs for networkx.readwrite.gml (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

long = int
unicode = str
unichr = chr

def read_gml(path, label: str = ..., destringizer: Incomplete | None = ...): ...
def parse_gml(lines, label: str = ..., destringizer: Incomplete | None = ...): ...
def generate_gml(G, stringizer: Incomplete | None = ...) -> None: ...
def write_gml(G, path, stringizer: Incomplete | None = ...) -> None: ...
