# Stubs for networkx.readwrite.json_graph.adjacency (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def adjacency_data(G, attrs: Incomplete = {"id": "id", "key": "key"}): ...
def adjacency_graph(data, directed: bool = False, multigraph: bool = True, attrs: Incomplete = {"id": "id", "key": "key"}): ...
