# Stubs for networkx.readwrite.json_graph.cytoscape (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def cytoscape_data(G, attrs: Incomplete | None = ...): ...
def cytoscape_graph(data, attrs: Incomplete | None = ...): ...
