# Stubs for networkx.readwrite.json_graph.jit (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def jit_graph(data, create_using: Incomplete | None = ...): ...
def jit_data(G, indent: Incomplete | None = ...): ...
