# Stubs for networkx.readwrite.json_graph.node_link (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def node_link_data(G, attrs: Incomplete | None = None): ...
def node_link_graph(data, directed: bool = False, multigraph: bool = True, attrs: Incomplete | None = None): ...
