from _typeshed import Incomplete

def node_link_data(G, attrs: Incomplete | None = None): ...
def node_link_graph(data, directed: bool = False, multigraph: bool = True, attrs: Incomplete | None = None): ...
