from _typeshed import Incomplete

def core_number(G): ...

find_cores = core_number

def k_core(G, k: Incomplete | None = None, core_number: Incomplete | None = None): ...
def k_shell(G, k: Incomplete | None = None, core_number: Incomplete | None = None): ...
def k_crust(G, k: Incomplete | None = None, core_number: Incomplete | None = None): ...
def k_corona(G, k, core_number: Incomplete | None = None): ...
