# Stubs for networkx.algorithms.covering (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def min_edge_cover(G, matching_algorithm: Incomplete | None = None): ...
def is_edge_cover(G, cover): ...
