from _typeshed import Incomplete

def cycle_basis(G, root: Incomplete | None = None): ...
def simple_cycles(G) -> None: ...
def recursive_simple_cycles(G): ...
def find_cycle(G, source: Incomplete | None = None, orientation: Incomplete | None = None): ...
def minimum_cycle_basis(G, weight: Incomplete | None = None): ...
