from _typeshed import Incomplete

def extrema_bounding(G, compute: str = ...): ...
def eccentricity(G, v: Incomplete | None = None, sp: Incomplete | None = None): ...
def diameter(G, e: Incomplete | None = None, usebounds: bool = False): ...
def periphery(G, e: Incomplete | None = None, usebounds: bool = False): ...
def radius(G, e: Incomplete | None = None, usebounds: bool = False): ...
def center(G, e: Incomplete | None = None, usebounds: bool = False): ...
