# Stubs for networkx.algorithms.dominating (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def dominating_set(G, start_with: Incomplete | None = None): ...
def is_dominating_set(G, nbunch): ...
