def maximal_matching(G): ...
def is_matching(G, matching): ...
def is_maximal_matching(G, matching): ...
def is_perfect_matching(G, matching): ...
def max_weight_matching(G, maxcardinality: bool = False, weight: str = "weight"): ...
