# Stubs for networkx.algorithms.minors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def quotient_graph(
    G,
    partition,
    edge_relation: Incomplete | None = ...,
    node_data: Incomplete | None = ...,
    edge_data: Incomplete | None = ...,
    relabel: bool = ...,
    create_using: Incomplete | None = ...,
): ...
def contracted_nodes(G, u, v, self_loops: bool = ...): ...

identified_nodes = contracted_nodes

def contracted_edge(G, edge, self_loops: bool = ...): ...
