# Stubs for networkx.algorithms.mis (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def maximal_independent_set(G, nodes: Incomplete | None = None, seed: Incomplete | None = None): ...
