# Stubs for networkx.algorithms.reciprocity (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def reciprocity(G, nodes: Incomplete | None = None): ...
def overall_reciprocity(G): ...
