# Stubs for networkx.algorithms.richclub (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def rich_club_coefficient(G, normalized: bool = True, Q: int = 100, seed: Incomplete | None = None): ...
