# Stubs for networkx.algorithms.threshold (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def is_threshold_graph(G): ...
def find_threshold_graph(G, create_using: Incomplete | None = None): ...
