# Stubs for networkx.algorithms.vitality (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def closeness_vitality(
    G, node: Incomplete | None = None, weight: Incomplete | None = None, wiener_index: Incomplete | None = None
): ...
