def not_implemented_for(*graph_types): ...
def open_file(path_arg, mode: str = "r"): ...
def nodes_or_number(which_args): ...
def preserve_random_state(func): ...
def random_state(random_state_index): ...

np_random_state = random_state

def py_random_state(random_state_index): ...
