from _typeshed import Incomplete

class MappedQueue:
    h: Incomplete
    d: Incomplete
    def __init__(self, data=None) -> None: ...
    def __len__(self): ...
    def push(self, elt): ...
    def pop(self): ...
    def update(self, elt, new) -> None: ...
    def remove(self, elt) -> None: ...
