# Stubs for networkx.generators.duplication (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def partial_duplication_graph(N, n, p, q, seed: Incomplete | None = None): ...
def duplication_divergence_graph(n, p, seed: Incomplete | None = None): ...
