# Stubs for networkx.generators.ego (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def ego_graph(G, n, radius: int = ..., center: bool = ..., undirected: bool = ..., distance: Incomplete | None = ...): ...
