# Stubs for networkx.generators.harary_graph (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def hnm_harary_graph(n, m, create_using: Incomplete | None = None): ...
def hkn_harary_graph(k, n, create_using: Incomplete | None = None): ...
