# Stubs for networkx.generators.line (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

from networkx.utils.decorators import *

def line_graph(G, create_using: Incomplete | None = ...): ...
def inverse_line_graph(G): ...
