# Stubs for networkx.generators.spectral_graph_forge (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def spectral_graph_forge(G, alpha, transformation: str = "identity", seed: Incomplete | None = None): ...
