# Stubs for networkx.generators.stochastic (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def stochastic_graph(G, copy: bool = True, weight: str = "weight"): ...
