# Stubs for networkx.generators.trees (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def prefix_tree(paths): ...
def random_tree(n, seed: Incomplete | None = None): ...
