# Stubs for networkx.algorithms.community.asyn_fluid (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def asyn_fluidc(G, k, max_iter: int = 100, seed: Incomplete | None = None): ...
