# Stubs for networkx.algorithms.community.community_generators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def LFR_benchmark_graph(
    n,
    tau1,
    tau2,
    mu,
    average_degree: Incomplete | None = ...,
    min_degree: Incomplete | None = ...,
    max_degree: Incomplete | None = ...,
    min_community: Incomplete | None = ...,
    max_community: Incomplete | None = ...,
    tol: float = ...,
    max_iters: int = ...,
    seed: Incomplete | None = ...,
): ...
