# Stubs for networkx.algorithms.community.label_propagation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def asyn_lpa_communities(G, weight: Incomplete | None = None, seed: Incomplete | None = None): ...
def label_propagation_communities(G) -> None: ...
