def is_biconnected(G): ...
def biconnected_component_edges(G) -> None: ...
def biconnected_components(G) -> None: ...
def biconnected_component_subgraphs(G, copy: bool = ...) -> None: ...
def articulation_points(G) -> None: ...
