def connected_components(G) -> None: ...
def connected_component_subgraphs(G, copy: bool = ...) -> None: ...
def number_connected_components(G): ...
def is_connected(G): ...
def node_connected_component(G, n): ...
