# Stubs for networkx.algorithms.operators.unary (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import TypeVar

from networkx.classes.digraph import DiGraph

_T = TypeVar("_T")

def complement(G): ...
def reverse(G: DiGraph[_T], copy: bool = True) -> DiGraph[_T]: ...
