from _typeshed import Incomplete

def hopcroft_karp_matching(G, top_nodes: Incomplete | None = None): ...
def eppstein_matching(G, top_nodes: Incomplete | None = None): ...
def to_vertex_cover(G, matching, top_nodes: Incomplete | None = None): ...

maximum_matching = hopcroft_karp_matching
