# Stubs for networkx.algorithms.bipartite.spectral (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def spectral_bipartivity(G, nodes: Incomplete | None = None, weight: str = "weight"): ...
