# Stubs for networkx.drawing.nx_pylab (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def draw(G, pos: Incomplete | None = ..., ax: Incomplete | None = ..., **kwds) -> None: ...
def draw_networkx(G, pos: Incomplete | None = ..., arrows: bool = ..., with_labels: bool = ..., **kwds) -> None: ...
def draw_networkx_nodes(
    G,
    pos,
    nodelist: Incomplete | None = ...,
    node_size: int = ...,
    node_color: str = ...,
    node_shape: str = ...,
    alpha: float = ...,
    cmap: Incomplete | None = ...,
    vmin: Incomplete | None = ...,
    vmax: Incomplete | None = ...,
    ax: Incomplete | None = ...,
    linewidths: Incomplete | None = ...,
    edgecolors: Incomplete | None = ...,
    label: Incomplete | None = ...,
    **kwds,
): ...
def draw_networkx_edges(
    G,
    pos,
    edgelist: Incomplete | None = ...,
    width: float = ...,
    edge_color: str = ...,
    style: str = ...,
    alpha: float = ...,
    arrowstyle: str = ...,
    arrowsize: int = ...,
    edge_cmap: Incomplete | None = ...,
    edge_vmin: Incomplete | None = ...,
    edge_vmax: Incomplete | None = ...,
    ax: Incomplete | None = ...,
    arrows: bool = ...,
    label: Incomplete | None = ...,
    node_size: int = ...,
    nodelist: Incomplete | None = ...,
    node_shape: str = ...,
    connectionstyle: Incomplete | None = ...,
    **kwds,
): ...
def draw_networkx_labels(
    G,
    pos,
    labels: Incomplete | None = ...,
    font_size: int = ...,
    font_color: str = ...,
    font_family: str = ...,
    font_weight: str = ...,
    alpha: float = ...,
    bbox: Incomplete | None = ...,
    ax: Incomplete | None = ...,
    **kwds,
): ...
def draw_networkx_edge_labels(
    G,
    pos,
    edge_labels: Incomplete | None = ...,
    label_pos: float = ...,
    font_size: int = ...,
    font_color: str = ...,
    font_family: str = ...,
    font_weight: str = ...,
    alpha: float = ...,
    bbox: Incomplete | None = ...,
    ax: Incomplete | None = ...,
    rotate: bool = ...,
    **kwds,
): ...
def draw_circular(G, **kwargs) -> None: ...
def draw_kamada_kawai(G, **kwargs) -> None: ...
def draw_random(G, **kwargs) -> None: ...
def draw_spectral(G, **kwargs) -> None: ...
def draw_spring(G, **kwargs) -> None: ...
def draw_shell(G, **kwargs) -> None: ...
def draw_planar(G, **kwargs) -> None: ...
