# Stubs for networkx.algorithms.approximation.clustering_coefficient (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def average_clustering(G, trials: int = 1000, seed: Incomplete | None = None): ...
