# Stubs for networkx.algorithms.approximation.kcomponents (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def k_components(G, min_density: float = 0.95): ...
