from _typeshed import Incomplete

def hits(G, max_iter: int = 100, tol: float = 1e-08, nstart: Incomplete | None = None, normalized: bool = True): ...
def authority_matrix(G, nodelist: Incomplete | None = ...): ...
def hub_matrix(G, nodelist: Incomplete | None = ...): ...
def hits_numpy(G, normalized: bool = ...): ...
def hits_scipy(G, max_iter: int = ..., tol: float = ..., normalized: bool = ...): ...
