# Stubs for networkx.algorithms.link_analysis.pagerank_alg (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def pagerank(
    G,
    alpha: float = 0.85,
    personalization: Incomplete | None = None,
    max_iter: int = 100,
    tol: float = 1e-06,
    nstart: Incomplete | None = None,
    weight: str = "weight",
    dangling: Incomplete | None = None,
): ...
def google_matrix(
    G,
    alpha: float = 0.85,
    personalization: Incomplete | None = None,
    nodelist: Incomplete | None = None,
    weight: str = "weight",
    dangling: Incomplete | None = None,
): ...
def pagerank_numpy(
    G, alpha: float = ..., personalization: Incomplete | None = ..., weight: str = ..., dangling: Incomplete | None = ...
): ...
def pagerank_scipy(
    G,
    alpha: float = ...,
    personalization: Incomplete | None = ...,
    max_iter: int = ...,
    tol: float = ...,
    weight: str = ...,
    dangling: Incomplete | None = ...,
): ...
