# Stubs for networkx.algorithms.shortest_paths.astar (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def astar_path(G, source, target, heuristic: Incomplete | None = None, weight: str = "weight"): ...
def astar_path_length(G, source, target, heuristic: Incomplete | None = None, weight: str = "weight"): ...
