# Stubs for networkx.linalg.graphmatrix (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def incidence_matrix(
    G, nodelist: Incomplete | None = ..., edgelist: Incomplete | None = ..., oriented: bool = ..., weight: Incomplete | None = ...
): ...
def adjacency_matrix(G, nodelist: Incomplete | None = ..., weight: str = ...): ...

adj_matrix = adjacency_matrix
