from _typeshed import Incomplete

def k_edge_components(G, k): ...
def k_edge_subgraphs(G, k): ...
def bridge_components(G) -> None: ...

class EdgeComponentAuxGraph:
    A: Incomplete
    H: Incomplete
    @classmethod
    def construct(cls, G): ...
    def k_edge_components(self, k) -> None: ...
    def k_edge_subgraphs(self, k) -> None: ...
