# Stubs for networkx.algorithms.connectivity.stoerwagner (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def stoer_wagner(G, weight: str = "weight", heap=...): ...
