from .digraph import DiGraph
from .graph import Graph, _Node
from .multidigraph import MultiDiGraph
from .multigraph import MultiGraph

class OrderedGraph(Graph[_Node]): ...
class OrderedDiGraph(DiGraph[_Node]): ...
class OrderedMultiGraph(MultiGraph[_Node]): ...
class OrderedMultiDiGraph(MultiDiGraph[_Node]): ...
