# Stubs for networkx.algorithms.assortativity.pairs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def node_attribute_xy(G, attribute, nodes: Incomplete | None = None) -> None: ...
def node_degree_xy(
    G, x: str = "out", y: str = "in", weight: Incomplete | None = None, nodes: Incomplete | None = None
) -> None: ...
