# Stubs for networkx.algorithms.node_classification.hmn (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def harmonic_function(G, max_iter: int = ..., label_name: str = ...): ...
