# Stubs for networkx.algorithms.traversal.beamsearch (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def bfs_beam_edges(G, source, value, width: Incomplete | None = None): ...
