from _typeshed import Incomplete

def bfs_edges(G, source, reverse: bool = False, depth_limit: Incomplete | None = None) -> None: ...
def bfs_tree(G, source, reverse: bool = False, depth_limit: Incomplete | None = None): ...
def bfs_predecessors(G, source, depth_limit: Incomplete | None = None) -> None: ...
def bfs_successors(G, source, depth_limit: Incomplete | None = None) -> None: ...
