# Stubs for networkx.algorithms.traversal.edgedfs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def edge_dfs(G, source: Incomplete | None = None, orientation: Incomplete | None = None): ...
