# Stubs for networkx.algorithms.flow.capacityscaling (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def capacity_scaling(G, demand: str = "demand", capacity: str = "capacity", weight: str = "weight", heap=...): ...
