# Stubs for networkx.algorithms.flow.edmondskarp (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

from networkx.algorithms.flow.utils import *

def edmonds_karp(
    G, s, t, capacity: str = ..., residual: Incomplete | None = ..., value_only: bool = ..., cutoff: Incomplete | None = ...
): ...
