# Stubs for networkx.algorithms.flow.networksimplex (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def network_simplex(G, demand: str = "demand", capacity: str = "capacity", weight: str = "weight"): ...
