# Stubs for networkx.algorithms.flow.preflowpush (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

def preflow_push(
    G,
    s,
    t,
    capacity: str = "capacity",
    residual: Incomplete | None = None,
    global_relabel_freq: int = 1,
    value_only: bool = False,
): ...
