# Stubs for networkx.algorithms.flow.shortestaugmentingpath (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from _typeshed import Incomplete

from .utils import *

def shortest_augmenting_path(
    G,
    s,
    t,
    capacity: str = "capacity",
    residual: Incomplete | None = None,
    value_only: bool = False,
    two_phase: bool = False,
    cutoff: Incomplete | None = None,
): ...
